# Generated by Django 5.0.3 on 2024-04-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_alter_client_fam_alter_client_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='fam',
            field=models.CharField(max_length=20, verbose_name='Фамилия'),
        ),
    ]
